version: "3.7"

services:
  app:
    image: pdf-downloader-app
    build: .
    restart: always
    environment:
      MAX_LIFE: 10000
    ports:
      - "3000:3000"
    volumes:
      - "files:/usr/src/app/public"

volumes:
  files:
